[package]
name = "linux-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
bluer = { version = "0.17.4", features = ["bluetoothd"] }
ecdsa = "0.16.9"
eyre = "0.6.12"
hex = "0.4.3"
p256 = { version = "0.13.2", features = ["ecdsa"] }
rand = { version = "0.10.0", features = ["thread_rng"] }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.50.0", features = ["full"] }
toml = "1.1.2"
xdg = "3.0.0"

[build-dependencies]
bindgen = "0.72.1"
